### ISSUE TITLE
issue with CPU used/using.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#465]
**Describe the bug**
Big issue with CPU - using double CPU of procent.

**Expected behaviour**
65 users is online + 2 bots. and using double CPU of procent...it's time to be fixed. ;/ 

**Screenshots**
![](https://i.gyazo.com/ecadf574d844af24acb50342ba156976.png)

**Logs**
N/A

**Environment information:**
 Operating system: (`4.9.0-8-amd64 - Debian 9.5`)
 TeaSpeak version: [1.2.19-beta-7]
 I am using `experimental_31`: (yes)

**Additional context**
It's a pretty big problem if it really can use that much!

**Comment by MikkelDK** [comment]
You mean like these?

```
threads:
  #Thread pool size for the ticking task of a VirtualServer
  #Do NOT TOUCH unless you're 100% sure!
  ticking: 5
  voice:
    #Max number of threads for command handling on the instance
    #Do NOT TOUCH unless you're 100% sure!
    execute_limit: 10
    #Threads per server for command executing
    #Do NOT TOUCH unless you're 100% sure!
    execute_per_server: 3
    #LibEvent events per server
    #Do NOT TOUCH unless you're 100% sure!
    events_per_server: 4
    #Minimum IO threads
    #Do NOT TOUCH unless you're 100% sure!
    io_min: 3
    #IO Thread increase per server
    #Do NOT TOUCH unless you're 100% sure!
    io_per_server: 4
    #Max IO threads
    #Do NOT TOUCH unless you're 100% sure!
    io_limit: 10

```
